baseURL = "https://about.nakamasato.com/sample-controller"
languageCode = "en-us"
title = "sample controller"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true


contentDir = "docs/content"
assetDir = "docs/assets"
archetypeDir = "docs/archetypes"


[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 10

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id="G-9NTB93RVPJ"
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Study sample controller step by step to have deep understanding of Kubernetes controller.'
  # homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Study sample controller step by step to have deep understanding of Kubernetes controller."
    meta_og_title = "Sample controller"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Study sample controller step by step to have deep understanding of Kubernetes controller."
    meta_twitter_card = "summary"
    meta_twitter_site = "@gymnstcs"
    meta_twitter_creator = "@gymnstcs"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
